NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/orgca-lab-8054-orgca-lab.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/orgca-lab-8054-orgca-lab.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/orgca-lab-8054-orgca-lab.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/orgca-lab-8054-orgca-lab.pem
    OrganizationalUnitIdentifier: orderer
