# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

    
networks:
  ${NETWORK_NAME}:    
       name: ${NETWORK_NAME}

    
        
services:

  ${TLSCA_NAME}:
    image: hyperledger/fabric-ca:1.5.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=${TLSCA_NAME}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=${TLSCAPORT}
    ports:
      - "${TLSCAPORT}:${TLSCAPORT}"
    command: sh -c 'fabric-ca-server start -b tlscaadmin:tlscaadminpw -d'
    volumes:
      - ../../../organizations/tlsca_certs/${ORGNAME_ALL_LOWER}:/etc/hyperledger/fabric-ca-server
    container_name: ${TLSCA_NAME} 
    networks:
      - ${NETWORK_NAME}

 
