apiVersion: batch/v1
kind: Job
metadata:
  name: create-lab-orgcerts
  namespace: skincare
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-lab-orgcerts
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: skincarepvc
      containers:
        - name: create-lab-orgcerts
          image: hyperledger/fabric-ca-tools:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /data
              name: data
          command:
            - /bin/sh
            - -c
            - cd /data; ./skincare_script_files/orgcerts_scripts/lab/orgcerts_lab.sh
      restartPolicy: Never
