export ORDERERNAME=$1
export ORDERERNAME_ALL_LOWER="${ORDERERNAME,,}"
export ORDERERNAME_ALL_UPPER="${ORDERERNAME^^}"
export ORDERERNAME_FIRST_UPPER="${ORDERERNAME_ALL_LOWER^}"



export PROJECT_NAME="skincare"
export CHANNELNAME="oyurchannel"
