apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skincarepvc
  namespace: skincare
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4050Mi
