NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/orgca-orderer-8056-orgca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/orgca-orderer-8056-orgca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/orgca-orderer-8056-orgca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/orgca-orderer-8056-orgca-orderer.pem
    OrganizationalUnitIdentifier: orderer
